In [1]:
! pip install pandas

Requirement already satisfied: pandas in d:\krish_naik\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\krish_naik\venv\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\krish_naik\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\krish_naik\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\krish_naik\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in d:\krish_naik\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
## Series --> It is one dimensional array like an object that hold any datatype.

data = [1,2,3,4,5]

series = pd.Series(data)
print("Series is :\n",series)

Series is :
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
### Create A Series for Dictionary

data = { 'a':1,'b':2,'c':3,'d':4}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
### Create a Dataframe by Dictionary

data ={
    'Name':['Andy','Marnus','Pluto'],
    'City': ['New York','Southampton','Budapest'],
    'Age':[23,45,56]
}

df =pd.DataFrame(data)
df
#print(type(df))

     Name         City  Age
0    Andy     New York   23
1  Marnus  Southampton   45
2   Pluto     Budapest   56

In [6]:
### Create a Dataframe by using dictionary

data =[
    ['Alice',34,'Paris'],['Mark',28,'Edinburg'],['Nans',24,'London']
]

df = pd.DataFrame(data,columns=['Name','Age','City'])
df

    Name  Age      City
0  Alice   34     Paris
1   Mark   28  Edinburg
2   Nans   24    London

In [7]:
## Read file from different sources

df= pd.read_csv("sales_data (1).csv")
df

,Order ID,Date,Customer Name,Product,Category,Quantity,Unit Price,Total Sales
0,1001,2023-01-01,Alice,Laptop,Electronics,1,1200,1200
1,1002,2023-01-03,Bob,Smartphone,Electronics,2,800,1600
2,1003,2023-01-05,Charlie,Tablet,Electronics,1,300,300
3,1004,2023-01-07,David,Monitor,Electronics,2,200,400
4,1005,2023-01-10,Eva,Printer,Electronics,1,150,150

In [8]:
### Accessing values from the dataset in Pandas
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}

df = pd.DataFrame(data)
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [9]:
### Accessing columens 

df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [10]:
df[['Name','Salary']]

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000

In [11]:
df.loc[0]
#df.iloc[0]

Name      Alice
Age          25
Salary    50000
Name: 0, dtype: object

In [12]:
### Accessing specific elements from dataset

print(df.at[1,'Age'])

30

In [15]:
df.at[1,'Age'] = 29
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   29   60000
2  Charlie   33   70000

In [13]:
### Accessing specific elements by using iat

df.iat[2,1] = 33
print(df.iat[2,1])

33

In [14]:
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   33   70000

In [60]:
### Add a column in Dataframe

df['City']=['Florida','New York','Texas']
df

      Name  Age  Salary      City
0    Alice   25   50000   Florida
1      Bob   30   60000  New York
2  Charlie   35   70000     Texas

In [61]:
### Remove Column in Dataframe

df.drop('City',axis=1,inplace=True)
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [62]:
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [63]:
df.describe()

        Age   Salary
count   3.0      3.0
mean   30.0  60000.0
std     5.0  10000.0
min    25.0  50000.0
25%    27.5  55000.0
50%    30.0  60000.0
75%    32.5  65000.0
max    35.0  70000.0

In [64]:
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [65]:
df_new=df.iat[2,1] = 34
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   34   70000

In [66]:
df.at[2,'Age']

np.int64(34)

In [67]:
df.loc[0:3,'Age']

0    25
1    30
2    34
Name: Age, dtype: int64

In [68]:
df.iloc[2:,[1]]

   Age
2   34

In [69]:
df

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   34   70000

In [70]:
df_new =df.copy()
new_data = {
    'Name': 'Shreya',
    'Age': 25,
    'Salary': 70000
}
df_new =pd.concat([df_new, pd.DataFrame([new_data])], ignore_index=True)
df_new

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   34   70000
3   Shreya   25   70000

In [71]:
df_merged = pd.merge(df,df_new,how ='outer',on= None)
df_merged

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   34   70000
3   Shreya   25   70000

In [72]:
import pandas as pd

data = {
    'Department': ['IT', 'HR', 'IT', 'HR', 'Finance', 'IT'],
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [50000, 40000, 60000, 45000, 70000, 55000]
}

df = pd.DataFrame(data)
print(df)

  Department Employee  Salary
0         IT        A   50000
1         HR        B   40000
2         IT        C   60000
3         HR        D   45000
4    Finance        E   70000
5         IT        F   55000

In [73]:
df.groupby('Department')['Salary'].mean()

Department
Finance    70000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64

In [74]:
df.groupby('Department')['Salary'].agg(['mean', 'sum', 'count'])

               mean     sum  count
Department
Finance     70000.0   70000      1
HR          42500.0   85000      2
IT          55000.0  165000      3

In [75]:
df.groupby('Department')['Salary'].apply(lambda x: x.max() - x.min())

Department
Finance        0
HR          5000
IT         10000
Name: Salary, dtype: int64

In [76]:
import pandas as pd

df1 = pd.DataFrame({
    'EmpID': [1, 2, 3],
    'Name': ['A', 'B', 'C']
})

df2 = pd.DataFrame({
    'EmpID': [1, 2, 4],
    'Salary': [50000, 60000, 70000]
})

In [77]:
pd.merge(df1, df2, on='EmpID', how='inner')

   EmpID Name  Salary
0      1    A   50000
1      2    B   60000

In [78]:
pd.merge(df1, df2, on='EmpID', how='left')

   EmpID Name   Salary
0      1    A  50000.0
1      2    B  60000.0
2      3    C      NaN

In [79]:
pd.merge(df1, df2, on='EmpID', how='right')

   EmpID Name  Salary
0      1    A   50000
1      2    B   60000
2      4  NaN   70000

In [80]:
pd.merge(df1, df2, on='EmpID', how='outer')

   EmpID Name   Salary
0      1    A  50000.0
1      2    B  60000.0
2      3    C      NaN
3      4  NaN  70000.0

In [81]:
df_join = df1.join(df2.set_index('EmpID'),on = 'EmpID',how = 'inner')
df_join

   EmpID Name  Salary
0      1    A   50000
1      2    B   60000

In [82]:
import pandas as pd

df = pd.DataFrame({
    'Region': ['North', 'South', 'West'],
    'Jan': [10000, 15000, 12000],
    'Feb': [11000, 14000, 13000],
    'Mar': [12000, 16000, 12500]
})

print(df)

  Region    Jan    Feb    Mar
0  North  10000  11000  12000
1  South  15000  14000  16000
2   West  12000  13000  12500

In [83]:
df_melt = pd.melt(
    df,
    id_vars=['Region'],
    var_name='Month',
    value_name='Sales'
)

print(df_melt)

  Region Month  Sales
0  North   Jan  10000
1  South   Jan  15000
2   West   Jan  12000
3  North   Feb  11000
4  South   Feb  14000
5   West   Feb  13000
6  North   Mar  12000
7  South   Mar  16000
8   West   Mar  12500

In [84]:
df_melt.groupby('Month')['Sales'].sum()

Month
Feb    38000
Jan    37000
Mar    40500
Name: Sales, dtype: int64

In [85]:
df_melt.groupby('Region')['Sales'].mean()

Region
North    11000.0
South    15000.0
West     12500.0
Name: Sales, dtype: float64

In [86]:
import pandas as pd

df_melt = pd.DataFrame({
    'Region': ['North', 'North', 'North', 'South', 'South', 'South', 'West', 'West', 'West'],
    'Month': ['Jan', 'Feb', 'Mar'] * 3,
    'Sales': [10000, 11000, 12000, 15000, 14000, 16000, 12000, 13000, 12500]
})

print(df_melt)

  Region Month  Sales
0  North   Jan  10000
1  North   Feb  11000
2  North   Mar  12000
3  South   Jan  15000
4  South   Feb  14000
5  South   Mar  16000
6   West   Jan  12000
7   West   Feb  13000
8   West   Mar  12500

In [87]:
df_pivot = df_melt.pivot(index='Region', columns='Month', values='Sales')

print(df_pivot)

Month     Feb    Jan    Mar
Region
North   11000  10000  12000
South   14000  15000  16000
West    13000  12000  12500

In [88]:
def is_prime(number):
    if number < 1 :
        return False
    for i in range(2, int(number**0.5 )+1):
        if number % i==0:
            return False
        return True

number =int(input("Enter the Number :"))
if is_prime(number):
    print(f"{number} is a prime number") 
else :
    print(f"{number} is not a prime number")

97 is a prime number